### ISSUE TITLE
Convert to Pure SwiftUI

### ISSUE THREAD

**Issue by SwiftiOSStudio** [oscbyspro/DiffableTextViews#83]
This appears to utilize UIKit. Please create a release with Pure SwiftUI and SwiftUI styled utilization

`
.environment(\.locale, Locale(identifier: "sv_SE"))

.onSetup(of: .diffableTextField) { 
$0.keyboard.view(.numberPad)
 }
`

most likely should be view models

**Comment by oscbyspro** [comment]
As an example on the last point, if Apple decides to expose the environment UIKeyboardType then it would be possible use

```swift
keyboardType(.decimalPad)
```

as it is possible with SwiftUI.TextField. But because Apple has made it private/internal, I can’t use it. The other SwiftUI-y option is to add a variant for each

```swift
diffableTextField_keyboardType(.decimalPad)
```

which is something I though about, but decided against. If you have an awesome pitch for why it would be better, I’m open to hear it. But as it stands, I don’t think it's the correct design decision.
